<a href="https://colab.research.google.com/github/dgonxalex80/futuros_soya/blob/main/Series_de_Tiempo_NM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
### ## Importar librerias
import pandas as pd
import datetime as dt
from datetime import date
import yfinance as yf

Descarga de datos

In [2]:
company = 'ZS=F' ## Simbolo del aceite de soya en yahoo

# Definir fecha de inicio y del día de hoy

start = dt.datetime(2010,1,1)
today = date.today()

### Conexión a la API de yahoo para descargar la información
df = yf.download(company, start , today)

### visualizar información de las ultimas filas

df.tail(10)

[*********************100%***********************]  1 of 1 completed

               Open     High      Low    Close  Adj Close  Volume
Date
2023-07-25  1521.75  1527.25  1502.75  1515.50    1515.50   25259
2023-07-26  1513.75  1558.00  1506.00  1546.25    1546.25   30605
2023-07-27  1549.00  1580.75  1529.25  1532.00    1532.00   25445
2023-07-28  1530.50  1531.50  1483.50  1486.75    1486.75   13888
2023-07-31  1486.50  1486.50  1430.25  1445.75    1445.75    2352
2023-08-01  1446.50  1465.00  1433.75  1446.75    1446.75    2092
2023-08-02  1447.25  1447.25  1420.25  1429.75    1429.75     744
2023-08-03  1431.00  1445.00  1424.75  1428.75    1428.75    1505
2023-08-04  1446.00  1446.00  1434.00  1444.00    1444.00     323
2023-08-07  1430.00  1430.00  1405.00  1414.50    1414.50     323